### ISSUE TITLE
Unable to run tests from CLI

### ISSUE THREAD

**Issue by zouloux** [Strider-CD/strider#1008]
Hi there,

I was trying to hook runs from git but when i'm using strider cli "runTest" command I got this :

`strider runTest -l ... -p ... -j project/test -b master -m "Hook" -d`

Strider is installed on ubuntu with `npm install -g strider`.

I got the same result when I try to call API from Node.js with http package. (happening on login call)

```
Login error { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' } undefined
````

Any idea ? Many thanks

**Comment by zouloux** [comment]
Seems working on 1.8.0 so I rolled back.
Also adding `NODE_ENV=production && ` before `strider`

**Comment by knownasilya** [comment]
What's the `&&` for?

**Comment by knownasilya** [comment]
Bug confirmed

**Comment by zouloux** [comment]
Thx,
`&&` is just to follow up several commands in one line.

**Comment by knownasilya** [comment]
you can drop it 👍  also, try using master, I just pushed up a possible fix.

**Comment by zouloux** [comment]
Cool ! Can I `npm install -g strider`, will it install the master ?

**Comment by knownasilya** [comment]
`npm install -g Strider-CD/strider` would

**Comment by zouloux** [comment]
Ok so I installed via `npm install -g Strider-CD/strider` I got no more error but nothing happens. No error in strider console.

I run via : `/home/glados/npm/bin/strider runTest -l ... -p ... -j ... -b "master" -m "message" -d`
I double checked e-mail / password / project / branch.
What i get from console :
`Job started`

When I try to launch from strider web interface, the job start but nothing in web console (and it stucked).

I installed the same plugins as previously.

So maybe this bug is patched and it doesn't work on my specific configuration.
Rolling back again to 1.8.0, will try this later, thanks anyway :)

**Comment by zouloux** [comment]
Hey all !

So, i tried to update strider today from 1.8.0 to 1.9.4 and I still get the issue.
When I run this command :

`NODE_ENV=production && /home/.../npm/bin/strider runTest -l ... -p ... -j "..." -b "master" -m "message" -d`

I got this in terminal

```Login error { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' } undefined```

Note, it is running under ubuntu 16 with .npmrc config to install global node modules inside user directory (this is to avoid sudo management on all node, pretty handy)

I install it through `npm install -g strider`

Retrying to install directly with `npm install -g Strider-CD/strider` but last time nothing worked with this version.

Many thanks :)

**Comment by zouloux** [comment]
Ok so with `npm install -g Strider-CD/strider` when I start with the `runTest` command it now says "Job started" but nothin in strider web interface. Also when I try to run a build from web interface, nothin happens at all.

**Comment by knownasilya** [comment]
Master shouldn't be fixed, regarding the cli testing.

**Comment by knownasilya** [comment]
Closing this since it's a duplicate of #1001, please continue discussion there 👍

**Comment by zouloux** [comment]
_Just a last message in this thread_

I also have more infos on this one, maybe it can help somehow.

When updating from 1.8.0, repo URI (with manual add) like this : `git@git-domain.com:git-repo.git` were returning error 500 in strider console. And strider:3000 screen was just black.

So now I found a workaround by entering URI this way : `ssh://git@git-domain.com:22/home/git-repo.git`

Kind of weird that it dropped after this particular version on my env but now this is all working, thanks !
